image: node:10-alpine

variables:
  PUBLIC_PATH: /srv/www/PROJECT_NAME.tld/

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

stages:
  - lint
  - deploy

lint:
  stage: lint
  except:
    - staging
  script:
    - yarn clean
    - yarn lint

deploy:
  stage: deploy
  only:
    - develop
    - staging
    - master
  script:
    - yarn clean
    - API_ENV=${CI_COMMIT_REF_NAME} yarn webpack:prod
    - cp -rp dist ${PUBLIC_PATH}${CI_COMMIT_REF_NAME}_new
    - mv ${PUBLIC_PATH}${CI_COMMIT_REF_NAME} ${PUBLIC_PATH}${CI_COMMIT_REF_NAME}_old
    - mv ${PUBLIC_PATH}${CI_COMMIT_REF_NAME}_new ${PUBLIC_PATH}${CI_COMMIT_REF_NAME}
    - rm -rf ${PUBLIC_PATH}${CI_COMMIT_REF_NAME}_old
