image: node:latest

variables:
  PUBLIC_PATH: /srv/www/PROJECT_NAME.tld/

cache:
  key: "${CI_COMMIT_REF_NAME}"
  paths:
    - node_modules/
    - dist/

stages:
  - prepare
  - lint
  - build
  - deploy

prepare:
  stage: prepare
  script:
    - yarn clean

lint:
  stage: lint
  except:
    - staging
  script:
    - yarn lint

build_develop:
  stage: build
  only:
    - develop
  script:
    - API_ENV=staging yarn webpack:prod

build_staging:
  stage: build
  only:
    - staging
  script:
    - API_ENV=staging yarn webpack:prod

build_master:
  stage: build
  only:
    - master
  script:
    - API_ENV=production yarn webpack:prod

deploy:
  stage: deploy
  only:
    - develop
    - staging
    - master
  script:
    - cp -rp dist ${PUBLIC_PATH}${CI_COMMIT_REF_NAME}_new
    - mv ${PUBLIC_PATH}${CI_COMMIT_REF_NAME} ${PUBLIC_PATH}${CI_COMMIT_REF_NAME}_old
    - mv ${PUBLIC_PATH}${CI_COMMIT_REF_NAME}_new ${PUBLIC_PATH}${CI_COMMIT_REF_NAME}
    - rm -rf ${PUBLIC_PATH}${CI_COMMIT_REF_NAME}_old
